name: Dispatch AI Daily Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for git push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: '18'

      - name: Initialize news_archive.json if it does not exist
        run: |
          if [ ! -f news_archive.json ]; then
            echo "{}" > news_archive.json
          fi

      - name: Install dependencies
        run: npm install

      - name: Run the report script
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: node send_final_report.js

      - name: Commit and push updated news
